<a href="https://colab.research.google.com/github/xuanpeichu-2025/WIA1007-Week-3/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a = np.array([[1,2],[1,2]])
print(a)

[[1 2]
 [1 2]]


In [9]:
b = np.random.random((3,4))
print(b)

[[0.28367597 0.91774594 0.08707184 0.776723  ]
 [0.59863817 0.27493957 0.70324565 0.36580203]
 [0.73702801 0.12872319 0.98666218 0.02644455]]


In [5]:
n1 = np.zeros((2,2))
print(n1)

[[0. 0.]
 [0. 0.]]


In [7]:
n2 = np.ones((2,2))
print(n2)

[[1. 1.]
 [1. 1.]]


In [13]:
n3 = np.random.random((6,3))
print(n3)
print(n3.T)

[[0.60666337 0.49827358 0.34359107]
 [0.54934849 0.4215774  0.96948131]
 [0.97460331 0.04317462 0.96075444]
 [0.09942083 0.69926289 0.49617748]
 [0.87911331 0.63007583 0.99167006]
 [0.45556674 0.36553342 0.58303841]]
[[0.60666337 0.54934849 0.97460331 0.09942083 0.87911331 0.45556674]
 [0.49827358 0.4215774  0.04317462 0.69926289 0.63007583 0.36553342]
 [0.34359107 0.96948131 0.96075444 0.49617748 0.99167006 0.58303841]]


In [14]:
n4 = np.random.random((2,3))
n5 = np.random.random((3,4))
print(np.dot(n4,n5))

[[0.7434221  0.51379769 0.5484618  0.46887072]
 [0.66616928 0.71475689 0.59660547 0.7058963 ]]


In [15]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive
!mkdir -p git_repos
%cd git_repos

Mounted at /content/drive
/content/drive/MyDrive
/content/drive/MyDrive/git_repos


In [16]:
# provide url of repository that you want to clone
!git clone https://github.com/xuanpeichu-2025/WIA1007-Week-3.git

Cloning into 'WIA1007-Week-3'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), done.
