<a href="https://colab.research.google.com/github/xuanpeichu-2025/WIA1007-Week-3/blob/main/push_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

In [8]:
a = np.array([[1,2],[1,2]])
print(a)

[[1 2]
 [1 2]]


In [9]:
b = np.random.random((3,4))
print(b)

[[0.69689707 0.52209026 0.94507133 0.5122821 ]
 [0.2668486  0.28662089 0.46255295 0.1846097 ]
 [0.13332955 0.82174454 0.05749526 0.7143563 ]]


In [10]:
n1 = np.zeros((2,2))
print(n1)

[[0. 0.]
 [0. 0.]]


In [11]:
n2 = np.ones((2,2))
print(n2)

[[1. 1.]
 [1. 1.]]


In [12]:
n3 = np.random.random((6,3))
print(n3)
print(n3.T)

[[0.14485468 0.74134428 0.71527657]
 [0.6888988  0.96636193 0.32126134]
 [0.69636544 0.67023017 0.70706284]
 [0.21183112 0.25602448 0.55378206]
 [0.98393178 0.06575583 0.87944781]
 [0.21076169 0.96897255 0.26675295]]
[[0.14485468 0.6888988  0.69636544 0.21183112 0.98393178 0.21076169]
 [0.74134428 0.96636193 0.67023017 0.25602448 0.06575583 0.96897255]
 [0.71527657 0.32126134 0.70706284 0.55378206 0.87944781 0.26675295]]


In [13]:
n4 = np.random.random((2,3))
n5 = np.random.random((3,4))
print(np.dot(n4,n5))

[[0.88527799 0.99021135 0.76351852 0.57494371]
 [0.41555764 0.5050931  0.40878473 0.28778819]]
